### ISSUE TITLE
Scrollmagic turning off highlight at certain scroll points

### ISSUE THREAD

**Issue by cjdd3b** [striblab/2018-voters-guide#2]
Hard to notice unless you scroll slowly, but here's some evidence:

<img width="995" alt="screen shot 2018-09-18 at 7 27 32 am" src="https://user-images.githubusercontent.com/947791/45687453-816dd900-bb14-11e8-9c00-face9ff88194.png">

If you can't fix tomorrow morning, one option is to leave it and fix it after launch (it's not a huge deal). Another quick fix is to hide the issue by changing the background color on the "active" class to white, then come up with a solution later.

**Comment by cjsinner** [comment]
Yeah I think I know why this is ......

**Comment by cjsinner** [comment]
I *think* this is mostly fixed, but who knows, maybe I'll try to turn on the indicators again and figure it out.
