### ISSUE TITLE
Names before issues on desktop

### ISSUE THREAD

**Issue by cjdd3b** [striblab/2018-voters-guide#5]
Again, more of a quibble. But I can see the case for having the names precede each issue on mobile for sure. But on desktop they look kinda weird and repetitive. I think we can trust readers to remember which candidate is in which column:

<img width="357" alt="screen shot 2018-09-18 at 7 56 07 am" src="https://user-images.githubusercontent.com/947791/45688945-538a9380-bb18-11e8-9852-96a3cc350a24.png">

Could do some CSS voodoo to hide names on desktop but show at responsive breakpoints.

**Comment by cjsinner** [comment]
I definitely had this set just for mobile initially and can easily revert to it.
