### ISSUE TITLE
Nav size on mobile

### ISSUE THREAD

**Issue by cjdd3b** [striblab/2018-voters-guide#7]
Another quibble. Would be nice to get vertical nav size down to one line on mobile:

<img width="289" alt="screen shot 2018-09-18 at 7 59 44 am" src="https://user-images.githubusercontent.com/947791/45689170-e3c8d880-bb18-11e8-8485-a02f417e69bc.png">

**Comment by cjsinner** [comment]
I definitely tried to get them to fit on one line but they’d have to be so small I worried that they’d be hard to tap. We could trigger abbreviations on mobile maybe that would fit better?
